module.exports = [
  { name: "Food", emoji: "🍔", type: "expense", isDefault: true },
  { name: "Rent", emoji: "🏠", type: "expense", isDefault: true },
  { name: "Travel", emoji: "✈️", type: "expense", isDefault: true },
  { name: "Shopping", emoji: "🛍️", type: "expense", isDefault: true },
  { name: "Health", emoji: "💊", type: "expense", isDefault: true },
  { name: "Entertainment", emoji: "🎬", type: "expense", isDefault: true },
  { name: "Salary", emoji: "💰", type: "income", isDefault: true },
  { name: "Freelance", emoji: "🧑‍💻", type: "income", isDefault: true },
  { name: "Business", emoji: "🏢", type: "income", isDefault: true },
  { name: "Other", emoji: "🧾", type: "income", isDefault: true },
  { name: "Emergency Fund", emoji: "🚑", type: "savings", isDefault: true },
  { name: "Retirement", emoji: "👴", type: "savings", isDefault: true },
  { name: "Education", emoji: "🎓", type: "savings", isDefault: true },
  { name: "Other", emoji: "💼", type: "savings", isDefault: true },
];
